name: Test 1217 error - container
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  test1:
    runs-on: windows-latest

      env:
        PIP_ROOT_USER_ACTION: ignore
    
    strategy:
      matrix:
        python: [3.11.6]
    steps:
      - uses: actions/checkout@v4
    
      - name: Change ownership of /github/home
        run:  chown -R $(whoami) /github/home

      - name: Setup Python
        uses: actions/setup-python@v6
      
        with:
          python-version: ${{ matrix.python }}
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'
